apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-flask-app
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: my-flask-app
  template:
    metadata:
      labels:
        app: my-flask-app
    spec:
      containers:
      - name: my-flask-app
        image: odnatret/my-flask-app:latest
        ports:
        - containerPort: 5000
        resources:
          requests:
            cpu: "400m"
            memory: "128Mi"

