name: CICD Pipeline

on:
  push:
    branches: [ "master" ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/my-flask-app:${{ github.sha }}
      - name: Start Minikube
        run: |
          minikube start --driver=docker
          minikube kubectl -- apply -f kubernetes/ --validate=false
       - name: Get Minikube CA
         run: |
          minikube ssh "sudo cat /var/lib/minikube/certs/ca.crt" > minikubeCA.crt
          sudo cp minikubeCA.crt /usr/local/share/ca-certificates/
          sudo update-ca-certificates
      - name: Configure Kubernetes
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config
          kubectl config view
      - name: Deploy to Kubernetes
        run: |
          echo "${{ secrets.KUBE_CONFIG }}" > kubeconfig.yaml
          export KUBECONFIG=kubeconfig.yaml

          kubectl apply -f kubernetes/deployment.yaml --validate=false
          kubectl apply -f kubernetes/service.yaml --validate=false

